spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://arquserver.database.windows.net:1433;database=novasqlazure
    username: novasqlazure
    password: Sql321..
  security:
    user:
      name: nova
      password: 321

  mail:
    host: smtp.gmail.com
    port: 587
    username: andresolano34@gmail.com
    password: qnjjkxozztqhooma
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

spring.jpa:
  properties:
    hibernate:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.mvc:
  pathmatch:
    matching-strategy: ant-path-matcher

spring.main:
  banner-mode: off

spring.thymeleaf:
  cache: false

index:
  greet: hola martre
